name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        python-version: [3.11]
=======
        python-version: [3.10, 3.11]  # Test multiple Python versions in parallel
>>>>>>> c25e17160d65209584a99453db7ae56e3033c9ca

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
<<<<<<< HEAD
=======
        pip install pytest pytest-cov flake8 codecov
>>>>>>> c25e17160d65209584a99453db7ae56e3033c9ca

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests with pytest and generate coverage
      run: |
<<<<<<< HEAD
        pytest -n auto --cov=. --cov-report=xml:coverage.xml --cov-report=term --cov-fail-under=0
=======
        pytest -n auto --cov=. --cov-report=xml --cov-report=term --cov-fail-under=80
>>>>>>> c25e17160d65209584a99453db7ae56e3033c9ca
      env:
        PYTEST_ADDOPTS: "-p no:warnings"

    - name: Upload coverage to Codecov
<<<<<<< HEAD
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true
        flags: unittests


=======
      uses: codecov/codecov-action@v4
      with:
        files: coverage.xml
        fail_ci_if_error: true
        verbose: true
        flags: unittests
        # Codecov will post PR comments automatically
>>>>>>> c25e17160d65209584a99453db7ae56e3033c9ca
